url: https://jporzelt.github.io
baseurl:

# Site Settings
title: Johannes Porzelt
author: Johannes Porzelt
description: "Software Engineer. Project Manager."
keywords: "Johannes Porzelt, software engineering, project management, agile development, Java"
google-tracking-id:

# Color settings (hex-codes)
color:
  primary-dark: '#000000'
  primary-light: '#a1a1a1'
  links: '#a1a1a1'

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/jporzelt.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown", "build", "gradle"]

# Build settings
markdown: kramdown
permalink: pretty

encoding: utf-8
